# database
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/ems?characterEncoding-UTF-8&serverTimezone=UTC
    username: ems
    password: ems@123

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package : com.paging.mybatis.model;
